name: CI workflow
on:
  push:
    branches: [ dev, master ]
    tags:
      - '*.*.*'
  pull_request:
    branches: [ dev ]
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php: [7.4, 8.0]
        os: [ubuntu-20.04]
        wordpress: [6.0.3, latest]
        include:
          # TODO: replace this once this repo has unit tests and code coverage
          - experimental: false
#          - experimental: true
#          - experimental: false
#            php: 8.0
#            wordpress: 6.0.3

    name: Test - PHP ${{ matrix.php }} - WP ${{ matrix.wordpress }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start required services
        run: sudo systemctl start mysql.service

      - name: Cache PHP dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpcs, composer:v1
          coverage: pcov

      - name: Install PHP dependencies
        run: |
          export PATH="$HOME/.composer/vendor/bin:$PATH"
          composer install --no-interaction

      - name: Run PHP CodeSniffer
        run: composer standards
        if: matrix.experimental == false

    # TODO: Uncomment the following lines once this repo has unit tests

    #  - name: Install WP tests
    #    run: bash bin/install-wp-tests.sh wordpress_test root root localhost ${{ matrix.wordpress }}

    #  - name: Run PHP Tests
    #    run: composer test
    #    if: matrix.experimental == true

    #  - name: Run PHP Test and PCOV
    #    run: composer test-coverage
    #    if: matrix.experimental == false

    #  - name: Upload Coverage to Codecov
    #    run: bash <(curl -s https://codecov.io/bash)
    #    if: matrix.experimental == false
