name: 'Composer Autoupdate Trigger'
description: 'Triggers a Composer Autoupdate workflow in a Bedrock repository'
inputs:
  triggered-by:
    description: 'The name of the repository that triggered this workflow'
    required: true
  token:
    description: 'The GitHub token to use for the triggered workflow'
    required: true
  branch:
    description: 'The GitHub branch to use for the triggered workflow'
    required: true
outputs:
  workflow_id:
    description: 'The ID of the workflow that was triggered'
runs:
  using: 'node16'
  main: 'dist/index.js'
