name: "Compouser Update Automerge"

on:
  pull_request:
    branches: [main]

jobs:
  worker:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'Composer update with') 
    steps:
      - name: automerge
        uses: actions/github-script@0.2.0
        with:
          script: |
            github.pullRequests.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: ${{github.token}}