name: Pressbooks Auto updater

on:
  schedule:
    - cron: '*/5 * * * *' #UTC

jobs:
  composer_update_job:
    runs-on: ubuntu-latest
    name: composer update
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: composer update action
        uses: kawax/composer-update-action@master
        env:
          GITHUB_TOKEN: ${{github.token}}
          COMPOSER_PACKAGES: 'pressbooks/*'