name: Pressbooks composer updater

on:
  workflow_call:

jobs:
  composer_update_job:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.1 ]
        os: [ ubuntu-20.04 ]
    name: composer update
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          tools: composer
          php-version: ${{ matrix.php }}
      - name: Add HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json
      - name: composer update action
        uses: kawax/composer-update-action@master
        env:
          GITHUB_TOKEN: ${{secrets.PAT_FOR_GITHUB_ACTIONS}}
          GIT_NAME: Pressbooks 🤖
          GIT_EMAIL: ops@pressbooks.com
          APP_SINGLE_BRANCH: 1
          GIT_COMMIT_PREFIX: 'chore: '
          COMPOSER_PACKAGES: 'pressbooks/*'
