name: Pressbooks auto merge
on:
  workflow_call:

jobs:
  automerge:
    if: startsWith(github.event.pull_request.title, 'Composer update with')
    runs-on: ubuntu-latest
    steps:
      - name: Approve Composer auto update PRs
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{secrets.PAT_FOR_GITHUB_ACTIONS}}
        with:
          result-encoding: string
          script: |
            github.rest.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
          github-token: ${{github.token}}
