name: Pressbooks auto merge
on:
  workflow_call:

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Check Pull Request Title
        id: title-check
        run: |
          echo "shouldMerge=$(echo ${{ github.event.pull_request.title }} | grep -q '^chore: Composer update with' && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: Merge Composer auto update PRs
        if: steps.title-check.outputs.shouldMerge == 'true'
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{secrets.PAT_FOR_GITHUB_ACTIONS}}
        with:
          result-encoding: string
          script: |
            github.rest.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            }).then(() => {
              github.rest.pulls.listReviews({
                owner: context.payload.repository.owner.login,
                repo: context.payload.repository.name,
                pull_number: context.payload.pull_request.number
              }).then((reviews) => {
                const approvingReviews = reviews.data.filter(review => review.state === 'APPROVED')
                if (approvingReviews.length > 0) {
                  github.rest.pulls.merge({
                    owner: context.payload.repository.owner.login,
                    repo: context.payload.repository.name,
                    pull_number: context.payload.pull_request.number
                  })
                }
              })
            })
          github-token: ${{github.token}}
