name: "Auto merge"
on:
  pull_request_target:
    types: [opened]
  workflow_call:

jobs:
  automerge:
    if: startsWith(github.event.pull_request.title, 'Composer update with')
    runs-on: ubuntu-latest
    steps:
      - name: Merge composer update PRs
        uses: actions/github-script@0.2.0
        env:
          GITHUB_TOKEN: ${{secrets.PAT_FOR_GITHUB_ACTIONS}}
        with:
          script: |
            github.pullRequests.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: ${{github.token}}
