name: "Listen for Pressbooks plugin updates"
on:
  workflow_call:

jobs:
  trigger_bedrock_updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: '${{ github.repository_owner }}'  ,
              repo: 'composer-autoupdate-bedrock',
              workflow_id: 'update-bedrocks.yml',
              ref: 'main'
            })
